# Generated by Django 3.2 on 2022-11-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='inst_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
