# Generated by Django 3.2 on 2022-11-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_teaching_inst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.language')),
            ],
        ),
    ]
