# Generated by Django 3.2 on 2022-11-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
