# Generated by Django 3.2 on 2022-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20221127_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='academic',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='oneword',
            name='oneword',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reputation',
            name='reoutation',
            field=models.TextField(max_length=500),
        ),
    ]
