# Generated by Django 3.2 on 2022-11-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20221128_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
