# Generated by Django 3.2 on 2022-11-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_fee_fee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tl',
            new_name='teaching_langage',
        ),
    ]
