# Generated by Django 3.2 on 2022-11-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_rename_tl_teaching_langage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching_inst',
            name='teaching_inst1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_inst1', to='music.instrument'),
        ),
        migrations.AddField(
            model_name='teaching_inst',
            name='teaching_inst2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_inst2', to='music.instrument'),
        ),
        migrations.AddField(
            model_name='teaching_inst',
            name='teaching_inst3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_inst3', to='music.instrument'),
        ),
        migrations.AlterField(
            model_name='teaching_inst',
            name='teaching_inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_inst', to='music.instrument'),
        ),
    ]
