# Generated by Django 3.2 on 2022-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20221128_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
                ('academic', models.TextField(max_length=500)),
                ('experience', models.TextField(max_length=500)),
                ('certificate', models.TextField(max_length=500)),
                ('reputation', models.TextField(max_length=500)),
                ('message', models.TextField(max_length=500)),
                ('oneword', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='academic',
        ),
        migrations.DeleteModel(
            name='certificate',
        ),
        migrations.DeleteModel(
            name='experience',
        ),
        migrations.DeleteModel(
            name='fee',
        ),
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='oneword',
        ),
        migrations.DeleteModel(
            name='reputation',
        ),
    ]
