# Generated by Django 3.2 on 2022-11-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20221128_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movie',
            field=models.URLField(blank=True, null=True),
        ),
    ]
