# Generated by Django 3.2 on 2022-11-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_user_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fee',
            field=models.IntegerField(max_length=10),
        ),
    ]
