# Generated by Django 3.2 on 2022-12-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20221129_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fee',
        ),
    ]
