# Generated by Django 3.2 on 2022-12-02 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_remove_user_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
