# Generated by Django 3.2 on 2022-12-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20221202_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching_inst',
            name='revel',
        ),
        migrations.RemoveField(
            model_name='teaching_inst',
            name='year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reputation',
        ),
        migrations.AddField(
            model_name='teaching_inst',
            name='teaching_inst1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_inst1', to='music.instrument'),
        ),
        migrations.AddField(
            model_name='teaching_inst',
            name='teaching_inst2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_inst2', to='music.instrument'),
        ),
        migrations.AddField(
            model_name='teaching_inst',
            name='teaching_inst3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_inst3', to='music.instrument'),
        ),
    ]
