# Generated by Django 3.2 on 2022-12-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.teaching_inst'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.teaching_langage'),
        ),
    ]
