# Generated by Django 3.2 on 2022-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20221203_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching_inst',
            name='revel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teaching_inst',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
