# Generated by Django 3.2 on 2022-12-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20221203_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching_inst',
            name='teaching_inst1',
        ),
        migrations.RemoveField(
            model_name='teaching_inst',
            name='teaching_inst2',
        ),
        migrations.RemoveField(
            model_name='teaching_inst',
            name='teaching_inst3',
        ),
    ]
