# Generated by Django 3.2 on 2022-12-04 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20221204_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.teacher_picture'),
        ),
    ]
