# Generated by Django 3.2 on 2022-12-04 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_auto_20221204_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='reputation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fee',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
