# Generated by Django 3.2 on 2022-12-17 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_auto_20221204_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching_langage',
            name='teaching_lang',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='inst_image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='inst',
        ),
        migrations.AddField(
            model_name='teacher',
            name='revel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_inst', to='music.instrument'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.language'),
        ),
        migrations.DeleteModel(
            name='teaching_inst',
        ),
        migrations.DeleteModel(
            name='teaching_langage',
        ),
    ]
