# Generated by Django 3.2 on 2022-12-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_auto_20221217_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lang',
        ),
        migrations.AddField(
            model_name='teacher',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.language'),
        ),
    ]
