# Generated by Django 3.2 on 2022-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_auto_20221217_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lang',
        ),
        migrations.AddField(
            model_name='teacher',
            name='lang',
            field=models.ManyToManyField(blank=True, null=True, to='music.language'),
        ),
    ]
