# Generated by Django 3.2 on 2022-12-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_auto_20221217_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lang',
            field=models.ManyToManyField(blank=True, to='music.language'),
        ),
    ]
