# Generated by Django 3.2 on 2022-11-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee',
            field=models.CharField(blank=True, max_length=3, verbose_name='last fee'),
        ),
    ]
