# Generated by Django 3.2 on 2022-11-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fee',
            field=models.CharField(blank=True, max_length=3, verbose_name='fee'),
        ),
    ]
