# Generated by Django 3.2 on 2022-11-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_musician',
            field=models.BooleanField(default=False, verbose_name='音楽家である'),
        ),
    ]
