# Generated by Django 3.2 on 2022-12-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name1',
            field=models.CharField(blank=True, max_length=30, verbose_name='苗字'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name1',
            field=models.CharField(blank=True, max_length=30, verbose_name='名前'),
        ),
    ]
