# Generated by Django 3.2 on 2022-12-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221230_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name1',
        ),
    ]
